theme: jekyll-theme-minimal
title: Windows Forms Expander
author: Ren&eacute; Vogt
description: An Expander control for Windows Forms.
#url: https://renevogt.github.io/WindowsFormsExpander/
baseurl: 
markdown: kramdown
